{
  imports = [
    ./attic.nix
    ./caddy.nix
    ./cloudflare-dyndns.nix
    ./cloudflared.nix
    ./nextcloud.nix
    ./ollama.nix
    ./openssh.nix
    ./forgejo.nix
    ./glance.nix
    ./hydra.nix
    ./jellyfin.nix
    ./system-logger
    ./syncthing.nix
    ./tailscale.nix
    ./vaultwarden.nix
    ./vscode-server.nix
    ./wanikani-bypass-lessons.nix
    ./wanikani-fetch-data
    ./wanikani-stats
  ];
}
