{
  imports = [
    ./services
    ./adb.nix
    ./arduino.nix
    ./common-packages.nix
    ./concentration.nix
    ./disable-hibernation.nix
    ./emulation.nix
    ./fonts.nix
    ./graphical-interface.nix
    ./home.nix
    ./i18n.nix
    ./minegrub.nix
    ./nix-settings.nix
    ./remote-builds.nix
    ./secrets.nix
    ./security.nix
    ./sound.nix
    ./users.nix
    ./wake-on-lan.nix
    ./getty.nix
  ];
}
