{
  imports = [
    ./adb.nix
    ./arduino.nix
    ./caddy.nix
    ./common-packages.nix
    ./concentration.nix
    ./disable-hibernation.nix
    ./emulation.nix
    ./fonts.nix
    ./forgejo.nix
    ./graphical-interface.nix
    ./i18n.nix
    ./jellyfin.nix
    ./nix-settings.nix
    ./remote-builds.nix
    ./secrets.nix
    ./sound.nix
    ./tailscale.nix
    ./users.nix
    ./wake-on-lan.nix
  ];
}
