name: Build and test the packages i maintain on Nixpkgs


on:
  # cron every hour at 3 minutes 00:03 AM, 01:03 AM etc.
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nixpkgs: [nixos-unstable, nixpkgs-unstable, master]
        platform: [x86_64-linux, aarch64-linux]
        myPackages: # TODO automate this list
          - python313Packages.runstats
          - python313Packages.fastmri
          - python312Packages.runstats
          - python312Packages.fastmri
          - python311Packages.runstats
          - python311Packages.fastmri
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            system = ${{ matrix.platform }}

      - name: Build my packages
        run: nix build --log-lines 300 -L "github:nixos/nixpkgs/${{ matrix.nixpkgs }}#${{ matrix.myPackages }}"
