name: Build and test the packages i maintain on Nixpkgs


on:
  # cron every hour at 3 minutes 00:03 AM, 01:03 AM etc.
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nixpkgs-branch: [nixos-unstable, nixpkgs-unstable, master] # TODO: add stable branch once they are available
        # platform: [x86_64-linux, aarch64-linux] #TODO: add aarch64-linux
        myPackages: # TODO automate this list
          - python313Packages.runstats
          - python313Packages.fastmri
          - python312Packages.runstats
          - python312Packages.fastmri
          - python311Packages.runstats
          - python311Packages.fastmri
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        # with:
        #   extra_nix_config: |
        #     # system = ${{ matrix.platform }}

      # i want to create .drv file and check if they exist in the nixos.cache
      # if they dont exist, i want to skip the build

      - name: Check if the dependencies are in the cache
        run: nix path-info --closure-size --eval-store auto --store https://cache.nixos.org 'github:nixos/nixpkgs/${{ matrix.nixpkgs-branch }}${{ matrix.myPackages }}^*'

      - name: Build my packages
        run: nix build -L "github:nixos/nixpkgs/${{ matrix.nixpkgs-branch }}#${{ matrix.myPackages }}"
